### ISSUE TITLE
Unable to validate my template

### ISSUE THREAD

**Issue by jonyeezs** [Microsoft/packer-hyperv#16]
I'm having issue validating my temple. Getting error: 

> fork/exec C:\HashiCorp\packer\packer-builder-hyperv-iso.exe: This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher.

Below is my OS version:

```
OS Name Microsoft Windows 8.1 Enterprise
Version 6.3.9600 Build 9600
```

The ISO i'm using for my builder: SW_DVD5_Windows_Svr_Std_and_DataCtr_2012_R2_64Bit_English_Core_MLF_X19-05182.ISO (which is a windows 2012 server bundled with standard and DataCenter)

**Comment by v-vlshch** [comment]
Did you download packer-builder-hyperv-iso.exe or built it on your devbox?

**Comment by jonyeezs** [comment]
The error is with downloading the packer.

building my own seem to work (to a certain extend). It's not running any of the shell commands. But that could just be me.

**Comment by jonyeezs** [comment]
What version of Packer will the plugin work with?
