### ISSUE TITLE
Does this support packer 0.85?

### ISSUE THREAD

**Issue by damianh** [Microsoft/packer-hyperv#18]

**Comment by at-heind** [comment]
I've had trouble getting it to build a VM using packer 0.8.6. And it stopped building with packer 0.8.0 (see issue #19).

I don't know if anyone at Microsoft Open Technologies is maintaining this ... but I hope to find a way to get it working myself ... but don't hold your breath.

**Comment by pbolduc** [comment]
I would recommend you focus your efforts on this: https://github.com/mitchellh/packer/pull/2576

**Comment by at-heind** [comment]
Ah! I've had a quick look at that pull request and the comments. @pbolduc, I think you just saved me a ton of problems.

I'll give it https://github.com/mitchellh/packer/pull/2576 a try ...
