### ISSUE TITLE
Possible license change for inclusion of builder into Packer

### ISSUE THREAD

**Issue by taliesins** [Microsoft/packer-hyperv#20]
https://github.com/mitchellh/packer/pull/2576

We have almost got Hyper-V builder included into Packer.  It is based off this builder.

But there are some stumbling blocks around copyright. I think Hashicorp wants a slight change to license header so that it can be included in Packer. Is there someone who we can talk to about the issue.

I know they have also included other Microsoft copyright files for the Azure builder (MIT license). So I dont think its impossible.

Hoping to come up with a solution that everyone is happy with.

Current Packer license:
https://github.com/mitchellh/packer/blob/master/LICENSE

**Comment by mwhooker** [comment]
Hi all,

Just got some clarity on what we need before merging into packer main line. Unfortunately, going forward we can't have copyright attribution and code has to be licensed under the MPL 2.0 and cannot have copyright attribution.

Sorry for the last-minute notice on this. I'm just learning about it myself.

**Comment by batzen** [comment]
Ping @vladimir-shcherbakov

**Comment by vladimir-shcherbakov** [comment]
In progress. I let you know when it's done.

**Comment by taliesins** [comment]
Thanks :-)

**Comment by paulmey** [comment]
I have the official approval to contribute this code to mitchellh/packer under MPL 2.0. @mwhooker Will it work if I add MPL 2.0 as an alternative license to the LICENSE file?
